-- DEPRECATED: This file is superseded by 20260303_MASTER_FIX.sql
-- Do NOT run this file. It references the user_roles table which causes
-- infinite recursion. The MASTER_FIX handles super admin setup correctly.
-- Kept for reference only.
