-- DEPRECATED: This file is superseded by 20260303_MASTER_FIX.sql
-- Do NOT run this file. The MASTER_FIX uses hardcoded UUID for profiles
-- super admin policies instead of user_roles (which caused infinite recursion).
-- Kept for reference only.
